### ISSUE TITLE
cannot load such file -- sinatra/config_file (LoadError)

### ISSUE THREAD

**Issue by cschaffner** [netsuso/foos-tournament#5]
When trying to install the project, the sinatra config_file cannot be found. It is required in the first line of conf.rb 
 
```
➜  dm git:(master) ✗ ruby upgrade_model.rb
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sinatra/config_file (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /ufs/schaffne/foos-tournament/conf.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /ufs/schaffne/foos-tournament/dm/data_model.rb:3:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from upgrade_model.rb:3:in `<main>'
```

For your information, here is the list of installed gems:
```
➜  dm git:(master) ✗ gem list

*** LOCAL GEMS ***

addressable (2.5.1)
backports (3.8.0)
bcrypt (3.1.11)
bcrypt-ruby (3.1.5)
bigdecimal (1.2.8)
daemons (1.2.4)
data_mapper (1.2.0)
data_objects (0.10.17)
did_you_mean (1.0.0)
dm-aggregates (1.2.0)
dm-constraints (1.2.0)
dm-core (1.2.1)
dm-do-adapter (1.2.0)
dm-migrations (1.2.0)
dm-serializer (1.2.2)
dm-sqlite-adapter (1.2.0)
dm-timestamps (1.2.0)
dm-transactions (1.2.0)
dm-types (1.2.2)
dm-validations (1.2.0)
do_sqlite3 (0.10.17)
eventmachine (1.2.5)
fastercsv (1.5.5)
io-console (0.4.5)
json (1.8.3)
json_pure (1.8.6)
multi_json (1.12.1)
mustermann (1.0.0)
pathspec (0.0.2)
psych (2.1.0)
public_suffix (2.0.5)
rack (2.0.3)
rack-protection (2.0.0)
rdoc (4.2.2)
rgen (0.7.0)
safe_yaml (1.0.4)
sinatra (2.0.0)
sqlite3 (1.3.11)
stomp (1.3.5)
stringex (1.5.1)
thin (1.7.2)
tilt (2.0.8)
uuidtools (2.1.5)
```

**Comment by jacksmartv** [comment]
install ruby version 2.2.2 with Ruby Version Manager , after that install bundler and execute command "bundler install" in the folder where you cloned the code and do the README.md Steps.
Bye
